name: Stress Test Workflow

on:
  pull_request:
    branches: [master]

jobs:
  stress-test:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install stress-ng
      run: sudo apt-get update && sudo apt-get install -y stress-ng

    - name: Run stress-ng
      run: |
        echo "Starting stress test"
        stress-ng --cpu 4 --io 4 --vm 2 --vm-bytes 2G --timeout 300s --metrics-brief



