name: Python CI

on:
  pull_request:
    branches: [master]
  schedule:
  - cron: "5 * * * *"

jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
    - name: Printing message
      run: echo "Running every 5 mns"
  