name: Docker CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Dependencies
        working-directory: exercise_3
        run: | 
          pip install -r requirements.txt
          echo '${{ secrets.DOCKERHUB_USERNAME }}'
      
  docker:
      runs-on: ubuntu-latest
      steps:
        - 
          name: Checkout code
          uses: actions/checkout@v4
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/app:latest
            context: exercise_3
